name: Add Secrets to Key Vault

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev/qa)'
        required: true
        type: choice
        options:
          - dev
          - qa

      secrets_input:
        description: 'Secrets (key=value, one per line)'
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  add-secrets:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          case "${{ inputs.environment }}" in
            dev)
              echo "KV_NAME=rvcplatform-dev-keyvault" >> $GITHUB_ENV
              echo "YAML_FILE=installations/secrets/secret-provider-class-app-secrets-dev.yml" >> $GITHUB_ENV
              ;;
            qa)
              echo "KV_NAME=rvcplatform-qa-keyvault" >> $GITHUB_ENV
              echo "YAML_FILE=installations/secrets/secret-provider-class-app-secrets-qa.yml" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid environment"
              exit 1
              ;;
          esac

      - name: Show config
        run: |
          echo "ENV : ${{ inputs.environment }}"
          echo "KV  : $KV_NAME"
          echo "YAML: $YAML_FILE"

      - name: Install yq
        run: |
          sudo wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/bin/yq

      - name: Add Secrets to Key Vault
        run: |
          chmod +x cicd/scripts/keyvault.sh
          ./cicd/scripts/keyvault.sh "${{ inputs.secrets_input }}"

      - name: Update YAML Configuration
        run: |
          chmod +x cicd/scripts/yaml_update.sh
          ./cicd/scripts/yaml_update.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add $YAML_FILE

          git diff --cached --quiet && echo "No changes to commit" && exit 0

          git commit -m "🔐 Add secrets for ${{ inputs.environment }}"

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          title: "🔐 Add secrets (${{ inputs.environment }})"
          body: "Secrets added to Key Vault and YAML updated"
          branch: add-secrets-${{ github.run_id }}
          base: develop
          commit-message: "Add secrets for ${{ inputs.environment }}"

      - name: Summary
        run: |
          echo "=================================="
          echo "✅ Key Vault updated"
          echo "✅ YAML updated"
          echo "📄 File: $YAML_FILE"
          echo "=================================="
